Updating pages deploy script

diff --git a/publish-on-nist-pages b/publish-on-nist-pages
--- a/publish-on-nist-pages
+++ b/publish-on-nist-pages
@@ -5,6 +5,11 @@ PAGES_BRANCH=nist-pages
 MASTER_REMOTE=origin
 PAGES_REMOTE=origin
 BUILD_DIR=build
+opt_force=""
+
+if [ "$1" = "-f" ]; then
+  opt_force="-f"
+fi
 
 die() {
   echo "$@" >> /dev/stderr
@@ -23,14 +28,20 @@ fi
 
 cleanup
 
+status=$(git status --porcelain -b)
+echo $status | egrep -q '^##\smaster\.\.\.' || die "Must be run while master is checked out"
+changes=$(echo "$status" | egrep -v '^(##|\?\?)' | wc -l)
+if [ "$changes" -ne 0 -a -z "$opt_force" ]; then
+  die "You have uncommited changes - run with '-f' to force but CAUTION: CHANGES WILL BE LOST!"
+fi
 npm run build || die "'npm run build' failed" 
-git checkout -b $TEMP_BRANCH || die "Could not create branch $TEMP_BRANCH" # should bring over build directory
+git checkout $opt_force -b $TEMP_BRANCH || die "Could not create branch $TEMP_BRANCH" # should bring over build directory
 git add -f $BUILD_DIR || die "Could not add $BUILD_DIR to $TEMP_BRANCH"
 git commit -m "irrelevant commit for $PAGES_BRANCH generation" || die "Could not commit to $TEMP_BRANCH"
 git subtree split --prefix build -b "$PAGES_BRANCH" || die "'git subtree split' failed"
 git checkout master || die "'git checkout master' failed"
-#git push -f "${PAGES_REMOTE} ${PAGES_BRANCH}:${PAGES_BRANCH}" || die "'git push' failed"
+git push -f "${PAGES_REMOTE} ${PAGES_BRANCH}:${PAGES_BRANCH}" || die "'git push' failed"
 
-#cleanup
+cleanup
 
 exit 0
