Typo

diff --git a/publish-on-nist-pages b/publish-on-nist-pages
--- a/publish-on-nist-pages
+++ b/publish-on-nist-pages
@@ -19,7 +19,7 @@ die() {
 cleanup() {
   git branch -D "$TEMP_BRANCH" >/dev/null 2>&1  # Ignore errors; branch probably doesn't exist anyway 
   git branch -D "$PAGES_BRANCH" >/dev/null 2>&1  # Ignore errors; branch probably doesn't exist anyway
-  #rm -rf build
+  rm -rf build
 }
 
 if [ ! -d .git ]; then
@@ -40,7 +40,7 @@ git add -f $BUILD_DIR || die "Could not add $BUILD_DIR to $TEMP_BRANCH"
 git commit -m "irrelevant commit for $PAGES_BRANCH generation" || die "Could not commit to $TEMP_BRANCH"
 git subtree split --prefix build -b "$PAGES_BRANCH" || die "'git subtree split' failed"
 git checkout master || die "'git checkout master' failed"
-git push -f "${PAGES_REMOTE} ${PAGES_BRANCH}:${PAGES_BRANCH}" || die "'git push' failed"
+git push -f "${PAGES_REMOTE}" "${PAGES_BRANCH}:${PAGES_BRANCH}" || die "'git push' failed"
 
 cleanup
 
